#!/bin/sh
#wall=$(find "$WALLPAPERS" -type f | shuf -n 1)
#xwallpaper --zoom "$wall"

RAND=$(find "$WALLPAPERS" -type f | sort -R | head -1)
xwallpaper --zoom "$RAND"

# swww img "$wall" --transition-type any --transition-fps 120 > /dev/null
# wal -stn -i "$wall" > /dev/null
