#!/bin/sh
wall=$(find "$WALLPAPERS" -type f | shuf -n 1)
xwallpaper --zoom "$wall"
wal -stn -i "$wall" > /dev/null

#RAND=$(find "$WALLPAPERS" -type f | sort -R | head -1)
#xwallpaper --zoom "$RAND"

